---
# tasks file for configure-jumphost

- name: Show OS family
  debug:
    msg: "{{ ansible_os_family }}"

- name: Copy X1 files to jumphost
  copy:
    # Source path should point to root location of repo relative to
    # "configure-jumphost" role folder.
    src: "{{ item }}"
    dest: x1/
    mode: preserve
  loop:
    - ../../../ansible
    - ../../../terraform
    - ../../../x1
    - ../../../tests
    - ../../../scripts
    - ../../../pyproject.toml
  when: not use_git_archive

- name: Create git archive
  local_action:
    module: shell
    cmd: cd "$(git rev-parse --show-toplevel)" && git archive --format tgz --output /tmp/x1-$USER.tgz --prefix x1/ HEAD
  when: use_git_archive

- name: Copy git archive to the jumphost
  copy:
    src: /tmp/x1-{{ lookup('env', 'USER') }}.tgz
    dest: /tmp/x1.tgz
  when: use_git_archive

- name: Extract git archive
  command: tar zxf /tmp/x1.tgz
  when: use_git_archive

- name: Setup for Debian family
  include_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- name: Setup for RedHat family
  include_tasks: redhat.yaml
  when: ansible_os_family == "RedHat"

- name: Generate /etc/docker/daemon.json
  become: true
  copy:
    dest: /etc/docker/daemon.json
    content: "{{ lookup('template', 'docker-daemon.yaml') | from_yaml | to_json }}"

- name: Restart Docker
  become: true
  systemd:
    name: docker
    state: restarted

- name: Add user to docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    append: true
    groups: docker

# https://docs.docker.com/network/iptables/#docker-on-a-router
- name: Set the policy for the FORWARD chain to ACCEPT
  become: true
  iptables:
    chain: FORWARD
    policy: ACCEPT

# https://docs.docker.com/network/iptables/#docker-on-a-router
- name: ACCEPT rule in DOCKER-USER chain
  become: true
  iptables:
    chain: DOCKER-USER
    jump: ACCEPT
    action: insert

- name: Create jumphost scripts
  file:
    src: "x1/scripts/jumphost/{{ item }}"
    dest: "{{ item }}"
    state: link
  loop:
    - functions.sh
    - everything.sh
    - test.sh

- name: Generate ~/.x1
  file:
    path: ~/.x1
    state: directory

- name: Generate ~/.x1/environment
  template:
    src: templates/environment
    dest: ~/.x1/environment
    mode: 0755
