name: Build Rocky 9 image (docker)
on:
  workflow_dispatch:
  push:
    #    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: Build Rocky 9 image
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Run build
        run: |
          sh -vx
          docker stop packer-rocky9 || true
          docker rm packer-rocky9 || true

          gid=$(getent group kvm | awk -F : '{ print $3 }')
          sed -e "s/##KVM_GID##/$gid/" docker/Dockerfile.orig >Dockerfile
          cat Dockerfile

          docker build . \
            --build-arg http_proxy \
            --build-arg https_proxy \
            --build-arg no_proxy \
            --tag dataved/packer-rocky9

          docker run -id --device /dev/kvm --device /dev/fuse \
            --cap-add CAP_SYS_ADMIN --security-opt apparmor:unconfined \
            --name packer-rocky9 dataved/packer-rocky9
          
          docker exec packer-rocky9 sh -c 'git clone https://github.com/canonical/packer-maas && cd packer-maas/rocky9 && PACKER_LOG=1 make'
          docker cp packer-rocky9:/home/ghrunner/packer-maas/rocky9/rocky9.tar.gz .

      - uses: actions/upload-artifact@v3
        with:
          name: rocky9
          path: rocky9.tar.gz

