name: Multi node cluster with managed runners, Ubuntu, Kubespray

on:
  push:
    #    branches: [ main ]

  workflow_dispatch:

env:
  num_nodes: 4

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      nodes: ${{ steps.nodes.outputs.nodes }}
    steps:
      - id: nodes
        run: |
          nodes=$(python -c "print(list(range($num_nodes)))")
          echo nodes="$nodes" >>$GITHUB_OUTPUT

  control-node:
    runs-on: ubuntu-latest

    steps:
      - run: |
          hostname -i >control-node-ip.txt

      - name: Upload control node IP
        uses: actions/upload-artifact@v4
        with:
          name: control-node-ip.txt
          path: control-node-ip.txt

      - run: |
          sleep 200


  nodes:
    needs: [define-matrix]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        id: ${{ fromJSON(needs.define-matrix.outputs.nodes) }}

    steps:
      - run: |
          sleep 60

      - uses: actions/download-artifact@v4
        with:
          name: control-node-ip.txt

      - run: |
          set -vx
          echo ${{ matrix.id }}
          cat control-node-ip.txt
          hostname -i

