name: Multi node cluster with Vagrant, Ubuntu, Kubespray

on:
  push:
    #    branches: [ main ]

  workflow_dispatch:

env:
  num_nodes: 4

jobs:
  define-nodes:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "nodes='"$(python -c "print(list(range($num_nodes)))")"'" >>"$GITHUB_ENV"

  nodes:
    needs: define-nodes
    runs-on: ubuntu-latest
    env:
      nodes: "[0, 1, 2]"

    strategy:
      matrix:
        id: ${{ fromJSON(env.nodes) }}

    steps:
      - run: |
          echo ${{ matrix.id }}
