name: Multi node cluster with Vagrant, Ubuntu, Kubespray

on:
  push:
    #    branches: [ main ]

  workflow_dispatch:

env:
  num_nodes: 4

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      nodes: ${{ steps.nodes.outputs.nodes }}
    steps:
      - id: nodes
        run: |
          nodes=$(python -c "print(list(range($num_nodes)))")
          echo nodes="$nodes" >>$GITHUB_OUTPUT

  control-node:
    runs-on: ubuntu-latest
    outputs:
      control-node-ip: ${{ steps.ip.outputs.ip }}

    steps:
      - id: ip
        run: |
          echo ip=$(hostname -i) >>$GITHUB_OUTPUT

      - run: |
          sleep 200

  nodes:
    needs: [define-matrix, control-node]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        id: ${{ fromJSON(needs.define-matrix.outputs.nodes) }}

    steps:
      - run: |
          set -vx
          echo ${{ matrix.id }}
          echo ${{ needs.control-node.outputs.control-node-ip }}
          hostname -i

