name: Multi node cluster with Vagrant, Ubuntu, Kubespray

on:
  push:
    #    branches: [ main ]

  workflow_dispatch:

env:
  num_nodes: 4
  testd: $

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      nodes: $
    steps:
      - run: |
          nodes=$(python -c "print(list(range($num_nodes)))")
          echo nodes="$nodes" >>"$GITHUB_OUTPUT"
      - run: |
          echo ${{ fromJSON('[0, 1, 2]') }}

  nodes:
    needs: define-matrix
    runs-on: ubuntu-latest

    strategy:
      matrix:
        id: ${{ fromJSON(needs.define-matrix.outputs.nodes) }}

    steps:
      - run: |
          echo ${{ matrix.id }}
