name: Multi node cluster with Vagrant, Ubuntu, Kubespray

on:
  push:
    #    branches: [ main ]

  workflow_dispatch:

env:
  num_nodes: 4

jobs:
  define-nodes:
    runs-on: ubuntu-latest
    steps:
      run: |
        echo "nodes='"$(python -c "print(list(range($num_nodes)))")"'" >>"$GITHUB_ENV"

  nodes:
    needs: define-nodes
    runs-on: ubuntu-latest

    strategy:
      matrix:
        id: ${{ fromJSON(env.nodes) }}

    steps:
      - name: Print
        run: |
          echo ${{ matrix.id }}
