name: Single node cluster with Vagrant, Rocky Linux, Kind

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on:
      - self-hosted
      - libvirt-vagrant
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout x1-cluster-profiles repository
        uses: actions/checkout@v3
        with:
          repository: intel-sandbox/x1-cluster-profiles
          path: x1-cluster-profiles
          token: ${{ secrets.X1_GITHUB_TOKEN }}

      - name: Deploy a cluster on Vagrant VM
        run: ./scripts/ci/vagrant-rl-kind.sh

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs
          if-no-files-found: ignore
