name: Multi node cluster with Vagrant, Ubuntu, Kubespray

on:
  push:
    #    branches: [ main ]

  workflow_dispatch:

env:
  num_nodes: 4

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      nodes: ${{ steps.nodes.outputs.nodes }}
    steps:
      - id: nodes
        run: |
          nodes=$(python -c "print(list(range($num_nodes)))")
          echo nodes="$nodes" >>"$GITHUB_OUTPUT"

  nodes:
    needs: define-matrix
    runs-on: ubuntu-latest

    strategy:
      matrix:
        id: ${{ fromJSON(needs.define-matrix.outputs.nodes) }}

    steps:
      - run: |
          echo ${{ matrix.id }}
          ip addr

  control-node:
    runs-on: ubuntu-latest

    steps:
      - run: |
        ip addr




